const ideologies = [
    { name: 'Anarcho-Communism', econ: 'Collectivist', dipl: 'Anti-State', govt: 'Stateless', scty: 'Socially Progressive' },
    { name: 'Libertarian Communism', econ: 'Collectivist', dipl: 'Anti-State', govt: 'Stateless', scty: 'Socially Progressive' },
    { name: 'Trotskyism', econ: 'Collectivist', dipl: 'Internationalist', govt: 'Socialist State', scty: 'Socially Progressive' },
    { name: 'Marxism', econ: 'Collectivist', dipl: 'Internationalist', govt: 'Socialist State', scty: 'Socially Progressive' },
    { name: 'De Leonism', econ: 'Collectivist', dipl: 'Internationalist', govt: 'Socialist State', scty: 'Socially Progressive' },
    { name: 'Leninism', econ: 'Collectivist', dipl: 'Internationalist', govt: 'One-Party State', scty: 'Socially Progressive' },
    { name: 'Stalinism/Maoism', econ: 'Collectivist', dipl: 'Nationalist', govt: 'Totalitarian State', scty: 'Socially Conservative' },
    { name: 'Religious Communism', econ: 'Collectivist', dipl: 'Anti-State', govt: 'Theocratic', scty: 'Socially Conservative' },
    { name: 'State Socialism', econ: 'Collectivist', dipl: 'Nationalist', govt: 'Socialist State', scty: 'Socially Progressive' },
    { name: 'Theocratic Socialism', econ: 'Collectivist', dipl: 'Theocratic', govt: 'Socialist State', scty: 'Socially Conservative' },
    { name: 'Religious Socialism', econ: 'Collectivist', dipl: 'Theocratic', govt: 'Socialist State', scty: 'Socially Conservative' },
    { name: 'Democratic Socialism', econ: 'Mixed', dipl: 'Internationalist', govt: 'Democratic State', scty: 'Socially Progressive' },
    { name: 'Revolutionary Socialism', econ: 'Collectivist', dipl: 'Internationalist', govt: 'Proletarian State', scty: 'Socially Progressive' },
    { name: 'Libertarian Socialism', econ: 'Collectivist', dipl: 'Anti-State', govt: 'Stateless', scty: 'Socially Progressive' },
    { name: 'Anarcho-Syndicalism', econ: 'Collectivist', dipl: 'Anti-State', govt: 'Stateless', scty: 'Socially Progressive' },
    { name: 'Left-Wing Populism', econ: 'Mixed', dipl: 'Nationalist', govt: 'Democratic State', scty: 'Socially Progressive' },
    { name: 'Theocratic Distributism', econ: 'Mixed', dipl: 'Theocratic', govt: 'Distributist', scty: 'Socially Conservative' },
    { name: 'Distributism', econ: 'Mixed', dipl: 'Internationalist', govt: 'Distributist', scty: 'Socially Progressive' },
    { name: 'Social Liberalism', econ: 'Mixed', dipl: 'Internationalist', govt: 'Liberal Democracy', scty: 'Socially Progressive' },
    { name: 'Christian Democracy', econ: 'Mixed', dipl: 'Internationalist', govt: 'Democratic State', scty: 'Socially Conservative' },
    { name: 'Social Democracy', econ: 'Mixed', dipl: 'Internationalist', govt: 'Democratic State', scty: 'Socially Progressive' },
    { name: 'Progressivism', econ: 'Mixed', dipl: 'Internationalist', govt: 'Democratic State', scty: 'Socially Progressive' },
    { name: 'Anarcho-Mutualism', econ: 'Collectivist', dipl: 'Anti-State', govt: 'Stateless', scty: 'Socially Progressive' },
    { name: 'National Totalitarianism', econ: 'State-Controlled', dipl: 'Nationalist', govt: 'Totalitarian State', scty: 'Socially Conservative' },
    { name: 'Global Totalitarianism', econ: 'State-Controlled', dipl: 'Internationalist', govt: 'Totalitarian State', scty: 'Socially Conservative' },
    { name: 'Technocracy', econ: 'Controlled', dipl: 'Internationalist', govt: 'Technocratic State', scty: 'Socially Progressive' },
    { name: 'Centrist', econ: 'Mixed', dipl: 'Moderate', govt: 'Democratic State', scty: 'Neutral' },
    { name: 'Liberalism', econ: 'Mixed', dipl: 'Internationalist', govt: 'Liberal Democracy', scty: 'Socially Progressive' },
    { name: 'Religious Anarchism', econ: 'Collectivist', dipl: 'Anti-State', govt: 'Stateless', scty: 'Socially Conservative' },
    { name: 'Right-Wing Populism', econ: 'Mixed', dipl: 'Nationalist', govt: 'Democratic State', scty: 'Socially Conservative' },
    { name: 'Moderate Conservatism', econ: 'Mixed', dipl: 'Moderate', govt: 'Democratic State', scty: 'Socially Conservative' },
    { name: 'Reactionary', econ: 'Mixed', dipl: 'Conservative', govt: 'Monarchical State', scty: 'Socially Conservative' },
    { name: 'Social Libertarianism', econ: 'Mixed', dipl: 'Internationalist', govt: 'Democratic State', scty: 'Socially Progressive' },
    { name: 'Libertarianism', econ: 'Mixed', dipl: 'Internationalist', govt: 'Liberal Democracy', scty: 'Socially Progressive' },
    { name: 'Anarcho-Egoism', econ: 'Individualist', dipl: 'Anti-State', govt: 'Stateless', scty: 'Socially Progressive' },
    { name: 'Nazism', econ: 'State-Controlled', dipl: 'Nationalist', govt: 'Totalitarian State', scty: 'Socially Conservative' },
    { name: 'Autocracy', econ: 'State-Controlled', dipl: 'Nationalist', govt: 'Authoritarian State', scty: 'Socially Conservative' },
    { name: 'Fascism', econ: 'State-Controlled', dipl: 'Nationalist', govt: 'Totalitarian State', scty: 'Socially Conservative' },
    { name: 'Capitalist Fascism', econ: 'Capitalist', dipl: 'Nationalist', govt: 'Totalitarian State', scty: 'Socially Conservative' },
    { name: 'Conservatism', econ: 'Mixed', dipl: 'Conservative', govt: 'Democratic State', scty: 'Socially Conservative' },
    { name: 'Neo-Liberalism', econ: 'Capitalist', dipl: 'Internationalist', govt: 'Liberal Democracy', scty: 'Socially Progressive' },
    { name: 'Classical Liberalism', econ: 'Capitalist', dipl: 'Internationalist', govt: 'Liberal Democracy', scty: 'Socially Progressive' },
    { name: 'Authoritarian Capitalism', econ: 'Capitalist', dipl: 'Nationalist', govt: 'Authoritarian State', scty: 'Socially Conservative' },
    { name: 'State Capitalism', econ: 'State-Controlled', dipl: 'Nationalist', govt: 'Authoritarian State', scty: 'Socially Conservative' },
    { name: 'Neo-Conservatism', econ: 'Mixed', dipl: 'Nationalist', govt: 'Conservative State', scty: 'Socially Conservative' },
    { name: 'Fundamentalism', econ: 'Varies', dipl: 'Nationalist', govt: 'Theocratic State', scty: 'Socially Conservative' },
    { name: 'Libertarian Capitalism', econ: 'Capitalist', dipl: 'Internationalist', govt: 'Liberal Democracy', scty: 'Socially Progressive' },
    { name: 'Market Anarchism', econ: 'Individualist', dipl: 'Anti-State', govt: 'Stateless', scty: 'Socially Progressive' },
    { name: 'Objectivism', econ: 'Capitalist', dipl: 'Nationalist', govt: 'Liberal Democracy', scty: 'Socially Progressive' },
    { name: 'Totalitarian Capitalism', econ: 'State-Controlled', dipl: 'Nationalist', govt: 'Totalitarian State', scty: 'Socially Conservative' },
    { name: 'Ultra-Capitalism', econ: 'Capitalist', dipl: 'Internationalist', govt: 'Liberal Democracy', scty: 'Socially Progressive' },
    { name: 'Anarcho-Capitalism', econ: 'Capitalist', dipl: 'Anti-State', govt: 'Stateless', scty: 'Socially Progressive' }
];

export default ideologies;
